### ISSUE TITLE
Landing via c130sqf removes ability to throw grenades in a players inventory

### ISSUE THREAD

**Issue by Trenchf00tt** [BeowulfStratOps/bsoscripts#1]
![20220121093109_1](https://user-images.githubusercontent.com/98166712/150537576-67df554e-7e5b-4515-aa38-dc20bd5fe0a4.jpg)

After game on/ sqf is run and player lands, the grenades are not visible in the weapons corner.
Have to put grenades on the ground and pick them back up for them to be visible.

**Comment by bsoWalker** [comment]
@toadball

**Comment by toadball** [comment]
After testing on the test server:

It's a weird behaviour with Zade backpack / ArmA.
ArmA doesn't pick up what throwable the player has after switching backpack to/from chest/back until a reload action is done on the current throwable weapon or using the ace grenade throw key (presume there's some work around stuff going on there).
More accurately, it does not pick up on the throwables in the "new" backpack.

Test again and try using ace grenade throwing key (the one that gives the trajectory arc and throwing types dialog) after switching to regular backpack.

Being 100% upfront: I don't think a scripted work around is likely to be easy to do reliably, or imminent.

**Comment by Jsmuk** [comment]
So close as wontfix? I can't think of any possible workable solution either

**Comment by bsoWalker** [comment]
Think it would be a good idea to put something in the notes of the scripts to warn that this is a known issue with no workaround...

**Comment by toadball** [comment]
Sounds like a plan, only fix I can think of is redoing the Zade backpack functions used which would need done at the addon level. 
There's unfortunately no custom events to hook into for a backpack being swapped around which would have been the easiest option.

Will add note this evening with another small bugfix I've spotted before closing off.

**Comment by toadball** [comment]
Update to fixes and readme doc done. Closing off now.
